---
meta:
  default:
    azs:
      - (( replace ))
      - (( concat params.aws_region "a" ))

params:
  aws_key_name:    (( concat "vcap@" params.env ))
  aws_region:      (( param "What AWS region are you going to use?" ))
  aws_default_sgs: (( param "What security groups should VMs be placed in, if none are specified via Cloud Config?" ))

  stemcells:
    - name:    bosh-aws-xen-hvm-ubuntu-xenial-go_agent
      version: '170.25'
      url:     https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=170.25
      sha1:    33583a46ecc3eaa9f3be2a0187817a9b06367e36

releases:
  - name:    bosh-aws-cpi
    version: 73
    sha1:    350aa469deb281911b64d0be99faacfd26acdfaf
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=73

instance_groups:
- name: bosh
  jobs:
  - name: aws_cpi
    release: bosh-aws-cpi
  properties:
    aws:
      access_key_id:           (( vault meta.vault "/aws:access_key" ))
      secret_access_key:       (( vault meta.vault "/aws:secret_key" ))
      default_key_name:        (( grab params.aws_key_name ))
      default_security_groups: (( grab params.aws_default_sgs ))
      region:                  (( grab params.aws_region ))
    director:
      cpi_job: aws_cpi
