---
params:
  google_project: (( param "Enter the project name that your BOSH will be deployed into" ))

  ntp: # use GCP ntp
    - (( replace ))
    - time.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com

  stemcells:
    - name:    bosh-google-kvm-ubuntu-xenial-go_agent
      version: '170.25'
      url:     https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=170.25
      sha1:    f03d6263803ae88a50cbb54f2797207b0ea0d14a

releases:
  - name:    bosh-google-cpi
    version: 28.0.1
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-google-cpi-release?v=28.0.1
    sha1:    0020f77fbb7ac6de0698bdb5e7a64d338f2ca181

instance_groups:
- name: blacksmith
  jobs:
  - name: google_cpi
    release: bosh-google-cpi
  properties:
    google:
      project: (( grab params.google_project ))
      json_key: (( vault meta.vault "/google:json_key" ))
    director:
      cpi_job: google_cpi
