---
params:
  google_project: (( param "Enter the project name that your BOSH will be deployed into" ))

  ntp: # use GCP ntp
    - (( replace ))
    - time.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com

  stemcells:
    - name:    bosh-google-kvm-ubuntu-xenial-go_agent
      version: '621.55'
      url:     https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=621.55
      sha1:    eadbbd43d09bef7e2877cde032d68321444d10df

releases:
  - name:    bosh-google-cpi
    version: 30.0.0
    url:     https://bosh.io/d/github.com/cloudfoundry/bosh-google-cpi-release?v=30.0.0
    sha1:    fe4643b66f56dfd8a58df70b647bdc7d7e0c1273

instance_groups:
- name: blacksmith
  jobs:
  - name: google_cpi
    release: bosh-google-cpi
  properties:
    google:
      project: (( grab params.google_project ))
      json_key: (( vault meta.vault "/google:json_key" ))
    director:
      cpi_job: google_cpi
