---
params:
  google_project: (( param "Enter the project name that your BOSH will be deployed into" ))

  ntp: # use GCP ntp
    - (( replace ))
    - time.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com

  stemcells:
    - name:    bosh-google-kvm-ubuntu-trusty-go_agent
      version: '3468.17'
      url:     https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=3468.17
      sha1:    a5170583df951bff10a1e23183aae880890b8858

releases:
  - name:    bosh-google-cpi
    version: 27.0.1
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-google-cpi-release?v=27.0.1
    sha1:    1cd4e89aa2ba7479ad65a68ae520d104590a2c5b

instance_groups:
- name: bosh
  jobs:
  - name: google_cpi
    release: bosh-google-cpi
  properties:
    google:
      project: (( grab params.google_project ))
      json_key: (( vault meta.vault "/google:json_key" ))
    director:
      cpi_job: google_cpi
