---
meta:
  vsphere:
    ephemeral:  (( join "|" params.vsphere_ephemeral_datastores ))
    persistent: (( join "|" params.vsphere_persistent_datastores ))

params:
  vsphere_ephemeral_datastores:  (( param "Please specify your vSphere ephemeral datastore pattern" ))
  vsphere_persistent_datastores: (( param "Please specify your vSphere persistent datastore pattern" ))
  vsphere_clusters:              (( param "Please specify your vSphere clusters" ))
  vsphere_datacenter:            (( param "Please specify your vSphere Datacenter Name" ))

  stemcells:
    - name:    bosh-vsphere-esxi-ubuntu-xenial-go_agent
      version: '456.22'
      url:     https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=456.22
      sha1:    d18c43dfbb9b385ef749959d2d12b7947b617d92

releases:
  - name:    bosh-vsphere-cpi
    version: '52'
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release?v=52
    sha1:    94c6eea7d9e22125dbcbc5ecb7517533213258ef

instance_groups:
  - name: blacksmith
    jobs:
      - { release: bosh-vsphere-cpi, name: vsphere_cpi }

    properties:
      director:
        cpi_job: vsphere_cpi

      vcenter:
        address:  (( vault meta.vault "/vsphere:address"  ))
        user:     (( vault meta.vault "/vsphere:user"     ))
        password: (( vault meta.vault "/vsphere:password" ))

        datacenters:
          - name:     (( grab params.vsphere_datacenter ))
            clusters: (( grab params.vsphere_clusters   ))

            vm_folder:       (( concat params.env "-blacksmith/vms"       ))
            template_folder: (( concat params.env "-blacksmith/templates" ))
            disk_path:       (( concat params.env "-blacksmith/disks"     ))

            datastore_pattern:            (( concat "^(" meta.vsphere.ephemeral  ")$" ))
            persistent_datastore_pattern: (( concat "^(" meta.vsphere.persistent ")$" ))
