---
meta:
  kit:     blacksmith
  release: Blacksmith Genesis Kit
  target:  buf
  url:     https://10.200.131.2.netip.cc

  bosh:
    uri:      https://10.58.111.49:25555
    username: (( vault "secret/pipelines/genesis-ci/admin:username" ))
    password: (( vault "secret/pipelines/genesis-ci/admin:password" ))
    cacert:   (( vault "secret/pipelines/genesis-ci/ca:certificate" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  genesis-community
    repo:   blacksmith-genesis-kit
    branch: ci
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook:  (( vault "secret/pipelines/blacksmith-genesis-kit/slack:webhook" ))
    channel:  '#botspam'
    username: starkandwayne-ci
    icon:     https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
