---
params:
  stemcell_os:      ubuntu-trusty
  stemcell_version: latest
  availability_zones: [z1]

  network: blacksmith
  ip:      (( param "Please specify the static IP address for the Blacksmith Service Broker" ))

  vm_type:   blacksmith
  disk_size: 20480

  blacksmith_debug: false
  blacksmith_port:  3000
  blacksmith_env:   (( grab params.env )

  cloud_config: (( param "Please specify a complete BOSH v2 cloud-config, for the Blacksmith internal BOSH director to use" ))

  releases: []
  stemcells:
    - name:    bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: '3468.17'
      url:     https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3468.17
      sha1:    1691f18b9141ac59aec893a1e8437a7d68a88038

  # optional proxy support
  http_proxy:  ""
  https_proxy: ""
  no_proxy:    ""
